import * as path from 'path';
import * as fs from 'fs';

export type ExportEngine = 'unity' | 'unreal' | 'godot';

const ENGINE_BASE_PATHS: Record<ExportEngine, string> = {
  unity: 'Assets/Audio/SFX',
  unreal: 'Content/Audio/SFX',
  godot: 'assets/audio/sfx',
};

export async function exportToEngine(
  db: any,
  outputDir: string,
  engine: ExportEngine,
  sampleIds: number[]
): Promise<{ exported: number; errors: string[]; manifestPath: string }> {
  const basePath = path.join(outputDir, ENGINE_BASE_PATHS[engine]);
  let exported = 0;
  const errors: string[] = [];
  const manifest: Array<{ file: string; ucs: string; source: string }> = [];

  for (const sampleId of sampleIds) {
    const sample = db.prepare('SELECT id, file_name, file_path FROM samples WHERE id = ?').get(sampleId) as any;
    if (!sample) {
      errors.push(`Sample ${sampleId}: not found in DB`);
      continue;
    }

    const ucsTag = db.prepare(`
      SELECT uc.cat_code as cat, us.name_en as sub
      FROM sample_ucs_tags sut
      JOIN ucs_subcategories us ON sut.ucs_sub_id = us.id
      JOIN ucs_categories uc ON sut.ucs_cat_id = uc.id
      WHERE sut.sample_id = ? AND sut.is_confirmed = 1
      ORDER BY sut.confidence DESC LIMIT 1
    `).get(sampleId) as any;

    const relDir = ucsTag
      ? `${ucsTag.cat}/${ucsTag.sub || 'Other'}`
      : 'Unclassified';

    const targetDir = path.join(basePath, relDir);
    try {
      fs.mkdirSync(targetDir, { recursive: true });
    } catch (e: any) {
      errors.push(`${sample.file_name}: mkdir failed - ${e.message}`);
      continue;
    }

    const targetPath = path.join(targetDir, sample.file_name);
    try {
      fs.copyFileSync(sample.file_path, targetPath);
      exported++;
      manifest.push({
        file: path.join(ENGINE_BASE_PATHS[engine], relDir, sample.file_name).replace(/\\/g, '/'),
        ucs: ucsTag ? `${ucsTag.cat}/${ucsTag.sub}` : 'Unclassified',
        source: sample.file_path,
      });
    } catch (e: any) {
      errors.push(`${sample.file_name}: copy failed - ${e.message}`);
    }
  }

  // 写入 manifest.json
  const manifestPath = path.join(basePath, 'manifest.json');
  fs.writeFileSync(manifestPath, JSON.stringify({
    engine,
    exportedAt: new Date().toISOString(),
    totalExported: exported,
    files: manifest,
  }, null, 2), 'utf-8');

  return { exported, errors, manifestPath };
}

/** 生成 Godot AudioRegistry.gd 单例脚本 */
export function generateGodotRegistry(manifest: Array<{ file: string; ucs: string }>): string {
  const lines: string[] = [
    '# AudioRegistry.gd - Auto-generated by SamplerHub',
    '# Provides centralized access to all SFX paths',
    'extends Node',
    '',
    'const SFX = {',
  ];

  for (const m of manifest) {
    const key = path.basename(m.file, path.extname(m.file))
      .toUpperCase()
      .replace(/[^A-Z0-9]/g, '_')
      .replace(/^_|_$/g, '');
    lines.push(`  "${key}": "res://${m.file}",`);
  }

  lines.push('}');
  lines.push('');
  lines.push('# Usage: AudioRegistry.SFX.IMPACT_METAL_HIT_01');
  return lines.join('\n');
}
